### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by GPrimola** [GPrimola/jenkiexs#3]

**Comment by MrSoUndso** [comment]
Hi, I would like to try to build a ci pipeline for this project. However, I need a few informations first:
What ci service should be used? (GitHub Actions, CircleCi, TravisCi, something else?)
To add ci to a repo, you need write and/or admin acces to it. Can you grant me that?

**Comment by GPrimola** [comment]
Hey @MrSoUndso 

I really appreciate your interest! :D

I was thinking on having it as on GitHub Actions.
As for access, I want to share ownership of this repo, however I'll do so only for collabs, so I'd ask you to fork the repo and try on your own, as GitHub Actions is free for some amount of time that I think is more than enough for this case. :)

Thank you!

**Comment by MrSoUndso** [comment]
Hi @GPrimola,
I totally forgot I could fork a repo, how silly of me. I added a ci pipeline here, but it's currently failing (due to `mix test` failing)
I want to make further improvements to the pipeline once the tests run without issues, and i would also like to take issue #4 (the CD one)
