### ISSUE TITLE
[Unit Tests] Make unit test for Jenkiexs.Jobs.all/0

### ISSUE THREAD

**Issue by GPrimola** [GPrimola/jenkiexs#6]

**Comment by joseemds** [comment]
Hi!, can i try this one?

**Comment by GPrimola** [comment]
Hey @uduDudu thanks for the interest on the project!

Please, sure! Go ahead!

**Comment by joseemds** [comment]
I was trying here, for real i took this issue to learn more about jenkins and unit test, but jenkins are more complex than i thought, i think i will pass this issue to someone else who wants it and study alone
